<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function contactSearch($queryString)
    {
        if(empty($queryString)) {
            return $this->findAll();
        }

        $q = sprintf('%%%s%%', $queryString);

        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('c');

        $query = $qb
            ->where(
                $qb->expr()->orX(
                    $qb->expr()->like('c.name', ':queryString'),
                    $qb->expr()->like('c.phoneNumber', ':queryString'),
                    $qb->expr()->like('c.notes', ':queryString')
                )
            )
            ->setParameter('queryString', $q)
            ->getQuery();

        return $query->getResult();
    }
}
