<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Knp\Component\Pager\Paginator;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function contactSearch(Paginator $paginator, $queryString, $page=1, $limit=8)
    {
        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('c');

        if(!empty($queryString)) {
            {
                $q = sprintf('%%%s%%', $queryString);

                $qb
                    ->where(
                        $qb->expr()->orX(
                            $qb->expr()->like('c.name', ':queryString'),
                            $qb->expr()->like('c.phoneNumber', ':queryString'),
                            $qb->expr()->like('c.notes', ':queryString')
                        )
                    )
                    ->setParameter('queryString', $q);
            }
        }

        $contacts = $paginator->paginate(
            $qb,
            $page,
            $limit
        );

        return $contacts;
    }
}
